"""Updated сcomment_date

Revision ID: 5ab8d7a307c5
Revises: cf0b2e254a75
Create Date: 2025-07-22 14:40:58.741483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab8d7a307c5'
down_revision: Union[str, Sequence[str], None] = 'cf0b2e254a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
